config/routes.rb
Rails.application.routes.draw do
  get 'majors/autocomplete_major_name'
  get 'majors/search_major'
  get 'users/my_page'
  get 'users/my_reviews'
  get 'reviews/new'
  post 'reviews/new'
  get 'users/collected_reviews'
  get 'users/my_schools'

  resources :schools_majors, except: [:index]
  get 'majors/update_major_list', as: 'update_major_list'

  resources :majors
  devise_for :users

  root 'schools#school_reviews'

  get 'schools/autocomplete_school_name'
  get 'schools/search_school'

  # get 'reviews/write_review', as: 'write_a_review'
  resources :reviews, except: [:index] do
    collection do
      get 'major_list_options'
    end
  end

  resources :schools, except: [:index] do
    member do
      get 'reviews'
    end
  end

  get 'school_reviews', to: 'schools#school_reviews'
  get 'my_schools', to: 'schools#my_schools'

  resources :posts, except: [:show] do
    post "/like", to: "likes#like_toggle"
    resources :comments, only: [:create, :destroy]
  end
  resources :follows, only: [:create, :destroy]

  post 'review_like_toggle', to: 'reviews_likes#review_like_toggle'
  post 'school_like_toggle', to: 'schools_likes#school_like_toggle'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  # Can find out posts that a user liked
  # ex) user.likes_posts
  has_many :comments
  has_many :reviews
  # has_many :posts_likes
  has_many :reviews_likes
  has_many :schools_likes

  has_many :follower_relations, foreign_key: "followed_id", class_name: "Follow"
  has_many :followers, through: :follower_relations, source: :follower
  has_many :following_relations, foreign_key: "follower_id", class_name: "Follow"
  has_many :followings, through: :following_relations, source: :followed

  mount_uploader :avatar, AvatarUploader

  def is_like?(post)
    Like.find_by(user_id: self.id, post_id: post.id).present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorizeme
  def index
    @users = User.all
  end

  def my_page
  end

	def delete
		Review.destroy params[:rev]
		redirect_to user_my_reviews_delete_path
	end

  def my_reviews
    @reviews = current_user.reviews
  end

  def collected_reviews
    @liked_reviews = current_user.reviews_likes
  end

  def my_schools
    # liked schools
    @liked_schools = current_user.schools_likes.map {|schools_like| schools_like.school.name}
  end
end

app/views/users/collected_reviews.html.haml
%h1 My Liked Reviews
You have liked
= @liked_reviews.length
reviews.

%br
- @liked_reviews.each do |liked_review|
  %a{href: "/reviews/#{liked_review.review.id}"}
    %hr/
    %div
      %div{:align => "center"}
        %strong= liked_review.review.schools_major.school.name
        %br
        %strong= liked_review.review.schools_major.major.name
        %br
        %h3= liked_review.review.oneline_review
      %span{:style => "color: green;"} Pros
      %br
      - if liked_review.review.pro.present?
        = liked_review.review.pro[0,100] + ' ...'
      %br
      %br
      %span{:style => "color: red;"} Cons
      %br
      - if liked_review.review.con.present?
        = liked_review.review.con[0,100] + ' ...'
    %br

app/views/users/my_page.html.haml
= link_to("Edit Profile", edit_user_registration_path)
%br
%br
= link_to("My Own Reviews", users_my_reviews_path)
%br
%br
= link_to("My Liked Reviews", users_collected_reviews_path)
%br
%br
= link_to("My Schools", users_my_schools_path)

app/views/users/my_reviews.html.haml
%h1 My Own Reviews
You have
= @reviews.length
reviews.
%br
- @reviews.each do |review|
  %a{href: "/reviews/#{review.id}"}
    %hr/
    %div{:align => "center"}
      %strong= review.schools_major.school.name
      %br
      %strong= review.schools_major.major.name
      %br
      %h3= review.oneline_review
    %span{:style => "color: green;"} Pros
    %br
    - if review.pro.nil?
      = review.pro
    - else
      = review.pro[0,100] + ' ...'
    %br
    %br
    %span{:style => "color: red;"} Cons
    %br
    - if review.con.nil?
      = review.pro
    - else
      = review.con[0,100] + ' ...'
    %br
%hr/
%div{:align => "center"}
  #{button_to "Write a Review", reviews_new_path}

app/views/users/my_schools.html.haml
%h1 My Schools
You have liked
= @liked_schools.length
schools.
%br