config/routes.rb
Rails.application.routes.draw do
  get 'majors/autocomplete_major_name'
  get 'majors/search_major'
  get 'users/my_page'
  get 'users/my_reviews'
  get 'reviews/new'
  post 'reviews/new'
  get 'users/collected_reviews'
  get 'users/my_schools'

  resources :schools_majors, except: [:index]
  get 'majors/update_major_list', as: 'update_major_list'

  resources :majors
  devise_for :users

  root 'schools#school_reviews'

  get 'schools/autocomplete_school_name'
  get 'schools/search_school'

  # get 'reviews/write_review', as: 'write_a_review'
  resources :reviews, except: [:index] do
    collection do
      get 'major_list_options'
    end
  end

  resources :schools, except: [:index] do
    member do
      get 'reviews'
    end
  end

  get 'school_reviews', to: 'schools#school_reviews'
  get 'my_schools', to: 'schools#my_schools'

  resources :posts, except: [:show] do
    post "/like", to: "likes#like_toggle"
    resources :comments, only: [:create, :destroy]
  end
  resources :follows, only: [:create, :destroy]

  post 'review_like_toggle', to: 'reviews_likes#review_like_toggle'
  post 'school_like_toggle', to: 'schools_likes#school_like_toggle'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/major.rb
class Major < ApplicationRecord
  has_many :schools_majors
  has_many :schools, through: :schools_majors
  validates_presence_of :name

  def self.mapped_collection
    all.order(name: :asc).collect {|major| [ major.name, major.id ] }
  end
end

app/controllers/majors_controller.rb
class MajorsController < ApplicationController
  before_action :set_major, only: [:show, :edit, :update, :destroy]
  autocomplete :major, :name, full: true

  # GET /majors
  # GET /majors.json
  def index
    @majors = Major.all
  end

  # GET /majors/1
  # GET /majors/1.json
  def show
  end
  def update_major_list
    @school = School.find(params[:school])
    @courses = @school.majors.order("id asc").collect{|t| [t.id, t.name]}
    return render json: @courses
  end
  def search_major
    search = params[:major]
    @majors = Major.where("LOWER(majors.name) ILIKE '%#{search}%'")
  end

  # GET /majors/new
  def new
    @major = Major.new
  end

  # GET /majors/1/edit
  def edit
  end

  # POST /majors
  # POST /majors.json
  def create
    @major = Major.new(major_params)
    respond_to do |format|
      begin
      if @major.save
        format.html { redirect_to @major, notice: 'Major was successfully created.' }
        format.json { render :show, status: :created, location: @major }
      else
        format.html { render :new }
        format.json { render json: @major.errors, status: :unprocessable_entity }
      end
      rescue ActiveRecord::RecordNotUnique => e
        @major.errors.add(:name, "has already been taken. Please specify a different name.")
        format.html { render :new }
        format.json { render json: @major.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /majors/1
  # PATCH/PUT /majors/1.json
  def update
    respond_to do |format|
      if @major.update(major_params)
        format.html { redirect_to @major, notice: 'Major was successfully updated.' }
        format.json { render :show, status: :ok, location: @major }
      else
        format.html { render :edit }
        format.json { render json: @major.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /majors/1
  # DELETE /majors/1.json
  def destroy
    @major.destroy
    respond_to do |format|
      format.html { redirect_to majors_url, notice: 'Major was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_major
      @major = Major.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def major_params
      params.require(:major).permit(:name)
    end
end

app/helpers/majors_helper.rb
module MajorsHelper
end

app/views/majors/_form.html.haml
= form_for(major) do |f|
  - if major.errors.any?
    #error_explanation
      %h2
        = pluralize(major.errors.count, "error")
        prohibited this major from being saved:
      %ul
        - major.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit

app/views/majors/edit.html.haml
%h1 Editing Major
= render 'form', major: @major
= link_to 'Show', @major
|
= link_to 'Back', majors_path

app/views/majors/index.html.haml
%p#notice= notice
%h1 Majors
%table
  %thead
    %tr
      %th Name
      %th{:colspan => "3"}
  %tbody
    - @majors.each do |major|
      %tr
        %td= major.name
        %td= link_to 'Show', major
        %td= link_to 'Edit', edit_major_path(major)
        %td= link_to 'Destroy', major, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Major', new_major_path

app/views/majors/new.html.haml
%h1 New Major
= render 'form', major: @major
= link_to 'Back', majors_path

app/views/majors/search_major.html.haml
%h3 Search Major
= form_tag(majors_search_major_path, method: :get) do
  = text_field_tag :major, params[:major], class: "search-query", placeholder: "Search", type: "search", data: {autocomplete: majors_autocomplete_major_name_path}
  = submit_tag 'Search', name: ''

- if @majors.length > 0
  %ul
  - @majors.each do |major|
    %li= link_to(major.name, major_path(major))

app/views/majors/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @major.name
= link_to 'Edit', edit_major_path(@major)
|
= link_to 'Back', majors_path