config/routes.rb
Rails.application.routes.draw do
  get 'majors/autocomplete_major_name'
  get 'majors/search_major'
  get 'users/my_page'
  get 'users/my_reviews'
  get 'reviews/new'
  post 'reviews/new'
  get 'users/collected_reviews'
  get 'users/my_schools'

  resources :schools_majors, except: [:index]
  get 'majors/update_major_list', as: 'update_major_list'

  resources :majors
  devise_for :users

  root 'schools#school_reviews'

  get 'schools/autocomplete_school_name'
  get 'schools/search_school'

  # get 'reviews/write_review', as: 'write_a_review'
  resources :reviews, except: [:index] do
    collection do
      get 'major_list_options'
    end
  end

  resources :schools, except: [:index] do
    member do
      get 'reviews'
    end
  end

  get 'school_reviews', to: 'schools#school_reviews'
  get 'my_schools', to: 'schools#my_schools'

  resources :posts, except: [:show] do
    post "/like", to: "likes#like_toggle"
    resources :comments, only: [:create, :destroy]
  end
  resources :follows, only: [:create, :destroy]

  post 'review_like_toggle', to: 'reviews_likes#review_like_toggle'
  post 'school_like_toggle', to: 'schools_likes#school_like_toggle'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  
  has_many :likes
  has_many :reviews
  has_many :liked_users, through: :likes, source: :user
  has_many :comments
  
  mount_uploader :image, PostImageUploader
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # only for logged in users
  before_action :authenticate_user!
  before_action :check_ownership, only: [:edit, :update, :destroy]
  
  def index
    @posts = Post.all.order('created_at desc')
    @posts_count = current_user.posts.length
  end
  
  def new
  end
  
  def create
    # params[:image]를 받아서 image 컬럼에 추가
    new_post = Post.new(user_id: current_user.id, 
                        content: params[:content], 
                        image: params[:image])
    if new_post.save
      redirect_to root_path
    else
      redirect_to new_post_path
    end
  end
  
  def edit
  end
  
  def update
    @post.content = params[:content]
    
    if @post.save
      redirect_to root_path
    else
      render :edit
    end
  end
  
  def destroy
    @post.destroy
    redirect_to root_path
  end
  
  private

    def check_ownership
        @post = Post.find_by(id: params[:id])
        redirect_to root_path if @post.user.id != current_user.id
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.haml
.card.post
  .card-content
    .content
      %span.card-title= post.user.name
      %span= post.created_at
      - if user_signed_in? && current_user != post.user
        - if current_user.followings.include?(post.user)
          = form_tag follow_path(post.user.id), method: :delete, class: "right" do
            %button.btn Unfollow
        - else
          = form_tag follows_path, class: "right" do
            %input{:name => "followed_id", :type => "hidden", :value => "#{post.user.id}"}/
            %button.btn Follow
      .card-image
        - if post.image.url
          %img{:src => "#{post.image.url}"}/
      %p.pre-line= post.content
  .card-action
    = post.likes.size
    likes
    - if current_user.is_like?(post)
      = link_to "Cancel Like", post_like_path(post), method: "post"
    - else
      = link_to "Like", post_like_path(post), method: "post"
    - if current_user.id == post.user_id
      = link_to "delete", post_path(post), method: "delete", class: "right"
      = link_to "edit", edit_post_path(post), class: "right"
    = form_tag post_comments_path(post) do
      .input-field
        = text_area_tag :content, nil, class: "materialize-textarea", placeholder: "Write a comment", required: true
      .input-field
        = button_tag "Comment", class: "btn"
    - if post.comments.present?
      %ul.collection
        - post.comments.each do |comment|
          %li.collection-item
            %span.title= comment.user.name
            %span.right= comment.created_at
            %p.pre-line= comment.content
            - if comment.user.id == current_user.id
              %div= link_to "delete", post_comment_path(post, comment), method: "delete"

app/views/posts/edit.html.haml
.container
  .row
    .card.col.s12
      .card-content
        .card-title Edit Post
        = form_tag post_path(@post), method: "patch" do
          %input{:name => "id", :type => "hidden", :value => "#{@post.id}"}/
          .input-field
            = text_area_tag :content, @post.content, class: "materialize-textarea", placeholder: "Start here"
          .input-field
            = button_tag "edit", class: "btn"

app/views/posts/index.html.haml
.container
  .row
    .col.s12.m4
      .card
        .card-content
          .card-title= current_user.name
          %p
            Email: #{current_user.email}
          %p
            Posts: #{@posts_count}
          %p
            Follower: #{current_user.followers.length}
          %p
            Following: #{current_user.followings.length}
          = link_to new_post_path do
            %button.btn Post
    .col.s12.m8
      - @posts.each do |post|
        = render partial: "post", object: post

app/views/posts/new.html.haml
.container
  .row
    .card.col.s12
      .card-content
        .card-title Compose Post
        = form_tag posts_path, multipart: true do
          .input-field
            = file_field_tag :image
          .input-field
            = text_area_tag :content, nil, class: "materialize-textarea", placeholder: "Start here"
          .input-field
            = button_tag "post", class: "btn"