config/routes.rb
Rails.application.routes.draw do
  get 'majors/autocomplete_major_name'
  get 'majors/search_major'
  get 'users/my_page'
  get 'users/my_reviews'
  get 'reviews/new'
  post 'reviews/new'
  get 'users/collected_reviews'
  get 'users/my_schools'

  resources :schools_majors, except: [:index]
  get 'majors/update_major_list', as: 'update_major_list'

  resources :majors
  devise_for :users

  root 'schools#school_reviews'

  get 'schools/autocomplete_school_name'
  get 'schools/search_school'

  # get 'reviews/write_review', as: 'write_a_review'
  resources :reviews, except: [:index] do
    collection do
      get 'major_list_options'
    end
  end

  resources :schools, except: [:index] do
    member do
      get 'reviews'
    end
  end

  get 'school_reviews', to: 'schools#school_reviews'
  get 'my_schools', to: 'schools#my_schools'

  resources :posts, except: [:show] do
    post "/like", to: "likes#like_toggle"
    resources :comments, only: [:create, :destroy]
  end
  resources :follows, only: [:create, :destroy]

  post 'review_like_toggle', to: 'reviews_likes#review_like_toggle'
  post 'school_like_toggle', to: 'schools_likes#school_like_toggle'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/follow.rb
class Follow < ApplicationRecord
  # Relation : follower
  # Moden : User
  belongs_to :follower, class_name: "User"
  
  # Relation : followed
  # Moden : User
  belongs_to :followed, class_name: "User"
end

app/models/major.rb
class Major < ApplicationRecord
  has_many :schools_majors
  has_many :schools, through: :schools_majors
  validates_presence_of :name

  def self.mapped_collection
    all.order(name: :asc).collect {|major| [ major.name, major.id ] }
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  
  has_many :likes
  has_many :reviews
  has_many :liked_users, through: :likes, source: :user
  has_many :comments
  
  mount_uploader :image, PostImageUploader
end

app/models/posts_like.rb
class PostsLike < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/review.rb
require 'csv'
class Review < ApplicationRecord
  belongs_to :schools_major, class_name: SchoolsMajor, foreign_key: :schools_majors_id
  belongs_to :user

  has_many :reviews_likes

  # delegate :school, :major, to: :schools_major

  def name_or_anon
    self.anonymous? ? "Anonymous" : user.try(:name).to_s
  end

  def self.schools_major(school_id, major_id)
    SchoolsMajor.find_by(school_id: school_id, major_id: major_id)
  end

  def determine_user_type
    user_types = {
      '1': "Current Student",
      '2': "#{self.graduation_year} Graduate",
      '3': "Staff"
    }
    user_types[self.user_type.to_s.to_sym]
  end

  def has_graduation_year
		self.persisted? && self.graduation_year?
	end
 
  def self.import_review
		data = []
		CSV.foreach('db/seeds/reviews.csv', headers: true) do |row|
		  hash = row.to_hash
		  data << hash
		end

#		review_id = Review.last.id + 1
		#review = Review.find_by_id data_row[:review_id]
		data.each do |data_row|
      data_row.symbolize_keys!
		
			#review = Review.find_by_id data_row[:id]
			#if review
				#review.delete
			#end

    	puts "going to create"
			review = Review.new
#			review.id = review_id#data_row[:id].to_i
			review.schools_majors_id = data_row[:"schools_majors_id"].to_i
			review.user_id = data_row[:"user_id"].to_i
			review.pro = data_row[:pro]
			review.con = data_row[:con]
			review.advice = data_row[:advice]
			review.oneline_review = data_row[:"oneline_review"]
			review.rating_overall = data_row[:"rating_overall"].to_i
			review.rating_friendly = data_row[:"rating_friendly"].to_i
			review.rating_teaching = data_row[:"rating_teaching"].to_i
			review.rating_location = data_row[:"rating_location"].to_i
			review.rating_facilities = data_row[:"rating_facilities"].to_i
			review.rating_opportunity = data_row[:"rating_opportunity"].to_i
			review.rating_value = data_row[:"rating_value"].to_i
			review.recommended = data_row[:recommended].to_i
			review.user_type = data_row[:"user_type"]
			review.graduation_year = data_row[:"graduation_year"]
			review.save
#			review_id = review_id + 1
    end
  end
end

app/models/reviews_like.rb
class ReviewsLike < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/school.rb
require 'csv'
class School < ApplicationRecord
  #attr_accessible :picture

	has_many :schools_majors
	has_many :schools_likes
  has_many :majors, through: :schools_majors
  mount_uploader :picture, PictureUploader
  mount_uploader :logo, LogoUploader

  def one_line_comment
    "this is school one line comment."
  end

  def self.mapped_collection
    all.order(name: :asc).collect {|school| [ school.name, school.id ] }
  end

	def self.update_school_from_csv
		CSV.parse(File.read('db/seeds/schools.csv'), :headers => true).each do |row|
			school = School.find_by(id: row['id'], name: row['Name'], country: row['Country'])

			if school
				school.update_columns(oneline_review: row['oneline_review'])
			else
				school_params = {
					id: row['id'], name: row['Name'], country: row['Country'],
					state: row['State'], city: row['City'], url: row['Website'],
					oneline_review: row['oneline_review']
				}
				School.create(school_params)
			end
		end
	end

  def self.import_school_picture_path
    data = []
		CSV.foreach('db/seeds/schools.csv', headers: true) do |row|
			hash = row.to_hash
			data << hash
		end
		current_path = File.expand_path(File.dirname(__FILE__))
		images_path = File.expand_path("../assets/images", current_path)

		data.each do |data_row|
			data_row.symbolize_keys!
			school = nil
			school = School.find data_row[:id]

			unless data_row[:Picture].nil?
				path = images_path+"/"+data_row[:Picture]

				if school
					if File.exist?(path)
						file = File.open(path)
						school.picture=file
						school.save
					end
				end
			end
		end
  end
end

app/models/schools_like.rb
class SchoolsLike < ApplicationRecord
  belongs_to :user
  belongs_to :school
end
  

app/models/schools_major.rb
class SchoolsMajor < ApplicationRecord
  belongs_to :school
  belongs_to :major
  has_many :reviews, foreign_key: :schools_majors_id

  def display_name
    school_name = school.name
    major_name = major.name
    "#{school_name} #{major_name}"
  end

  def self.list_majors_of_school(school_id)
    data = {}
    schools_majors = self.includes(:school, :major).order('majors.name').where(school_id: school_id)

    schools_majors.map{|s_m| data["#{s_m.major.name}"] = "#{s_m.major.id}"}
    data.to_json
  end

  def rating_overall_averate
    all_review_ratings = self.reviews.pluck(:rating_overall)
    format("%.1f",(all_review_ratings.inject(0){|sum,x| sum + x }.to_f/ all_review_ratings.size))
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  # Can find out posts that a user liked
  # ex) user.likes_posts
  has_many :comments
  has_many :reviews
  # has_many :posts_likes
  has_many :reviews_likes
  has_many :schools_likes

  has_many :follower_relations, foreign_key: "followed_id", class_name: "Follow"
  has_many :followers, through: :follower_relations, source: :follower
  has_many :following_relations, foreign_key: "follower_id", class_name: "Follow"
  has_many :followings, through: :following_relations, source: :followed

  mount_uploader :avatar, AvatarUploader

  def is_like?(post)
    Like.find_by(user_id: self.id, post_id: post.id).present?
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/majors_helper.rb
module MajorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CampusReview.org
    = csrf_meta_tags
    /[if lte IE 8]
      = javascript_include_tag 'html5shiv'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    /[if lte IE 9]
      = stylesheet_link_tag "ie9.css"
    /[if lte IE 8]
      = stylesheet_link_tag "ie8.css"
    = stylesheet_link_tag    'style'
    = javascript_include_tag 'jquery.min'

    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width, initial-scale=1.0, user-scalable=no", :name => "viewport"}/
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css", :rel => "stylesheet"}
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"}

  %body
    / Wrapper
    #wrapper
      / Main
      #main
        .inner
          / Header
          %header#header
            %a.logo{:href => "/"}
              %strong Campus Review
            %ul.icons
              - if user_signed_in?
                %li
                  = current_user.name
              %li
                %a.icon.fa-search{:href => "/schools/search_school"}
                  %span.label Search
          / Banner

          %p.notice= notice
          %p.alert= alert
          = yield

      / Sidebar
      #sidebar
        .inner
          -# / Search
          -# %section#search.alt
          -#   = form_tag(schools_search_school_path, method: :get) do
          -#     = autocomplete_field_tag :school, params[:school], schools_autocomplete_school_name_path, class: "search-query", placeholder: "Search", type: "search"

          / Menu
          %nav#menu
            %header.major
              %h2 Menu
            %ul
              - if user_signed_in?
                %li
                  %a{:href => "/"} Home
                %li
                  = link_to("My Page", users_my_page_path)
                %li
                  = link_to("My Schools", users_my_schools_path)
                %li
                  = link_to("Write a Review", new_review_path)
                %li
                  = link_to("Search", schools_search_school_path)
                %li
                  = link_to("Log out", destroy_user_session_path, method: :get)
              - else
                %li
                  %a{:href => "/"} Home
                %li
                  = link_to("Write a Review", new_review_path)
                %li
                  = link_to("Search", schools_search_school_path)
                %li
                  = link_to("Sign up", new_user_registration_path)
                %li
                  = link_to("Log in", new_user_session_path)
          / Footer
          %footer#footer
            %p.copyright © NXTPath 2018
    / Scripts



    = javascript_include_tag 'skel.min'
    = javascript_include_tag 'util'
    /[if lte IE 8]
      = javascript_include_tag 'respond.min'
      = javascript_include_tag 'ie/respond.min'
    = javascript_include_tag 'main'